### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mzch** [scality/cloudserver#1780]
did npm install, then a fatal error occurred.

```
$ git checkout -b 8.1.9
Switched to a new branch '8.1.9'
$ npm install

> leveldown@1.6.0 install /srv/cloudserver/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)
make: Entering directory '/srv/cloudserver/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/batch.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/batch.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:833:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/batch.cc:1:0:
/home/objstr/.node-gyp/10.15.3/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/objstr/.node-gyp/10.15.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/batch.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:848:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../src/batch.cc:1:0:
/home/objstr/.node-gyp/10.15.3/include/node/node.h:170:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/objstr/.node-gyp/10.15.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/batch.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:863:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../src/batch.cc:1:0:
/home/objstr/.node-gyp/10.15.3/include/node/node.h:163:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/objstr/.node-gyp/10.15.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/batch.cc:3:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1477:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../src/batch.cc:1:0:
/home/objstr/.node-gyp/10.15.3/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/objstr/.node-gyp/10.15.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h: In function ‘size_t StringOrBufferLength(v8::Local<v8::Value>)’:
../src/leveldown.h:16:26: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return (!obj->ToObject().IsEmpty()
                          ^
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:17:48: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     && node::Buffer::HasInstance(obj->ToObject()))
                                                ^
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:18:42: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     ? node::Buffer::Length(obj->ToObject())
                                          ^
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/batch.cc:8:0:
../src/common.h: In function ‘uint32_t leveldown::UInt32OptionValue(v8::Local<v8::Object>, const char*, uint32_t)’:
../src/common.h:32:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     ? options->Get(key)->Uint32Value()
                                      ^
In file included from /home/objstr/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/objstr/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/batch.cc:42:76: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Database* database = Nan::ObjectWrap::Unwrap<Database>(info[0]->ToObject());
                                                                            ^
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::Put(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:91:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:92:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/batch.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE leveldown::Batch::Del(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/leveldown.h:53:30: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   } else if (!from->ToObject().IsEmpty()                                       \
                              ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:54:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       && node::Buffer::HasInstance(from->ToObject())) {                        \
                                                   ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:55:53: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                                     ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
In file included from ../src/database.h:18:0,
                 from ../src/batch.cc:5:
../src/leveldown.h:56:51: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                                   ^
../src/batch.cc:110:3: note: in expansion of macro ‘LD_STRING_OR_BUFFER_TO_SLICE’
   LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/objstr/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/batch.cc:1:
/home/objstr/.node-gyp/10.15.3/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
leveldown.target.mk:119: recipe for target 'Release/obj.target/leveldown/src/batch.o' failed
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory '/srv/cloudserver/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/cloudserver/node_modules/leveldown
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cdmiclient@github:scality/cdmiclient#rel/7.4 (node_modules/cdmiclient):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ERROR: Repository not found.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: Could not read from remote repository.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Please make sure you have the correct access rights
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: and the repository exists.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: exited with error code: 128
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/objstr/.npm/_logs/2019-04-16T08_05_30_760Z-debug.log
```

**Comment by rjdamore** [comment]
I've not been able to build the cloud server with node v10. I have only managed the build with v8.  Just an FYI, in case it could help.

**Comment by mzch** [comment]
I reinstalled node v8, but still an error occurred.

```
objstr@ny:/srv/cloudserver$ node -v
v8.11.1
objstr@ny:/srv/cloudserver$ npm -v
5.8.0
objstr@ny:/srv/cloudserver$ npm install
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/objstr/.npm/_logs/2019-04-16T17_03_27_112Z-debug.log
```

**Comment by mzch** [comment]
I tried the latest v8.

```
objstr@ny:/srv/cloudserver$ node -v
v8.15.1
objstr@ny:/srv/cloudserver$ npm -v
6.4.1
objstr@ny:/srv/cloudserver$ npm install

(snip)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cdmiclient@github:scality/cdmiclient#8f0c2e6 (node_modules/cdmiclient):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: /usr/bin/git ls-remote -h -t ssh://git@github.com/scality/cdmiclient.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ERROR: Repository not found.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: Could not read from remote repository.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Please make sure you have the correct access rights
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: and the repository exists.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: exited with error code: 128

added 777 packages from 807 contributors and audited 3488 packages in 591.215s
found 79 vulnerabilities (45 low, 12 moderate, 20 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

and got the following error logs:
```
{"name":"S3","error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8900},"method":"_crrMetricRequest","time":1555435409748,"req_id":"04c6f13f5344a9b65ff9","level":"error","message":"unable to perform request to backbeat api","hostname":"ny","pid":8097}
{"name":"S3","error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8900},"method":"getReplicationStates","service":"replication","time":1555435409750,"req_id":"04c6f13f5344a9b65ff9","level":"error","message":"unable to perform request to backbeat api","hostname":"ny","pid":8097}
```

Is this good?

**Comment by dora-korpar** [comment]
Hi @mzch, yes Cloudserver currently only works with Node v8. I'm not sure why v8.11 was giving you issues, as it should be able to run on any v8. But anyway, glad you got it installed.

What command did you run that produced those error logs?

**Comment by mzch** [comment]
'npm start' reported these errors.

**Comment by dora-korpar** [comment]
try running
'REMOTE_MANAGEMENT_DISABLE=1 npm start'
That should allow you to run CloudServer without it looking to connect to our frontend and other services, which is what was causing the errors

**Comment by mzch** [comment]
Thanks. I accessed 'http://localhost:8000/ and got the error message on my browser. What is lacking in my configuration?

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidURI</Code>
<Message>
Could not parse the specified URI. Check your restEndpoints configuration.
</Message>
<Resource/>
<RequestId>167138a05f418d060654</RequestId>
</Error>
```

**Comment by dora-korpar** [comment]
In your config.json, did you change anything in the 'restEndpoints' section? There should be a listing for 'localhost'

**Comment by mzch** [comment]
Oh, sorry, I accessed from another PC. I can access cloudserver from localhost. Thanks again!
