### ISSUE TITLE
Every objects Access Denied on getObject

### ISSUE THREAD

**Issue by jc-lab** [scality/cloudserver#2240]
I tested in version 8.2.3 (Same 8.1.18, 8.2.0) with docker

putObject works as a "write-api @ local" user.
But for any user getObject becomes Access Denied.
Changing acl with read-all is the same.

Environment variables are as follows.
REMOTE_MANAGEMENT_DISABLE = 1
ENDPOINT=my-domain.com

Bucket ACL
```
{
    "Owner": {
        "DisplayName": "...",
        "ID": "..."
    },
    "Grants": [
        {
            "Grantee": {
                "Type": "CanonicalUser",
                "DisplayName": "admin@local",
                "ID": "..."
            },
            "Permission": "FULL_CONTROL"
        },
        {
            "Grantee": {
                "Type": "CanonicalUser",
                "DisplayName": "write-api@local",
                "ID": "..."
            },
            "Permission": "WRITE"
        },
        {
            "Grantee": {
                "Type": "CanonicalUser",
                "DisplayName": "read-api@local",
                "ID": "..."
            },
            "Permission": "READ"
        }
    ]
}
```

Log data
```
{"name":"S3","time":1573128705359,"level":"warn","message":"scality kms unavailable. Using file kms backend unless mem specified.","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
{"name":"MetadataFileClient","time":1573128706117,"level":"info","message":"connecting to metadata service at http://localhost:9990/MDFile/metadata","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
{"name":"MetadataFileServer","time":1573128706323,"error":"Cannot find module 'ioctl'","errorStack":"Error: Cannot find module 'ioctl'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at trySetDirSyncFlag (/usr/src/app/node_modules/arsenal/lib/storage/utils.js:9:19)\n    at Object.setDirSyncFlag (/usr/src/app/node_modules/arsenal/lib/storage/utils.js:46:13)\n    at MetadataFileServer.startServer (/usr/src/app/node_modules/arsenal/lib/storage/metadata/file/MetadataFileServer.js:125:22)\n    at Object.<anonymous> (/usr/src/app/mdserver.js:28:14)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)","level":"warn","message":"WARNING: Synchronization directory updates are not supported on this platform. Newly written data could be lost if your system crashes before the operating system is able to write directory updates.","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":109}
{"name":"MetadataFileServer","time":1573128706325,"level":"info","message":"creating metadata service at /MDFile/metadata","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":109}
{"name":"MetadataFileServer","time":1573128706328,"level":"info","message":"creating record log service at /MDFile/recordLog","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":109}
{"name":"MetadataFileServer","time":1573128706329,"level":"info","message":"starting metadata file backend server","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":109}
{"name":"MetadataFileServer","time":1573128706336,"level":"info","message":"This deployment's identifier is eaeb9ec0-3aa7-4d95-9abd-27bc6916de8f","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":109}
{"name":"DataFileStore","time":1573128706369,"level":"info","message":"pre-creating 3511 subdirs...","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":112}
{"name":"DataFileStore","time":1573128706371,"error":"Cannot find module 'ioctl'","errorStack":"Error: Cannot find module 'ioctl'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at trySetDirSyncFlag (/usr/src/app/node_modules/arsenal/lib/storage/utils.js:9:19)\n    at Object.setDirSyncFlag (/usr/src/app/node_modules/arsenal/lib/storage/utils.js:46:13)\n    at fs.access.err (/usr/src/app/node_modules/arsenal/lib/storage/data/file/DataFileStore.js:92:30)\n    at FSReqWrap.args [as oncomplete] (fs.js:140:20)","level":"warn","message":"WARNING: Synchronization directory updates are not supported on this platform. Newly written data could be lost if your system crashes before the operating system is able to write directory updates.","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":112}
{"name":"DataFileStore","time":1573128706580,"level":"info","message":"data file store init complete, go forth and store data.","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":112}
{"name":"DataFileRESTServer","time":1573128706581,"method":"arsenal.network.Server.start","port":9991,"level":"info","message":"starting Server under http","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":112}
{"name":"DataFileRESTServer","time":1573128706585,"method":"arsenal.network.Server._onListening","address":{"address":"127.0.0.1","family":"IPv4","port":9991},"level":"info","message":"Server is listening","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":112}
{"name":"S3","time":1573128707130,"https":false,"level":"info","message":"Http server configuration","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
{"name":"S3","time":1573128707132,"address":"::","port":8000,"pid":71,"level":"info","message":"server started","hostname":"cloudserver-s3-6946f45bc9-ln5sf"}
{"name":"S3","time":1573128712133,"req_id":"840daa8e174b839c7413","level":"info","message":"remote management disabled","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
{"name":"S3","clientIP":"::ffff:172.30.2.0","clientPort":41294,"httpMethod":"GET","httpURL":"/test-bucket/9e97e39b-19da-459c-8c57-b47e6d53e271/file/905c906fa2a6925cb0c4c18de9092e16","time":1573128719661,"req_id":"ab33e72e904897939092","level":"info","message":"received request","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
{"name":"S3","bucketName":"test-bucket","objectKey":"9e97e39b-19da-459c-8c57-b47e6d53e271/file/905c906fa2a6925cb0c4c18de9092e16","bytesReceived":0,"bodyLength":0,"bytesSent":174,"clientIP":"::ffff:172.30.2.0","clientPort":41294,"httpMethod":"GET","httpURL":"/test-bucket/9e97e39b-19da-459c-8c57-b47e6d53e271/file/905c906fa2a6925cb0c4c18de9092e16","contentLength":0,"httpCode":403,"time":1573128719691,"req_id":"ab33e72e904897939092","elapsed_ms":30.120483,"level":"info","message":"responded with error XML","hostname":"cloudserver-s3-6946f45bc9-ln5sf","pid":71}
```

**Comment by dashagurova** [comment]
Hello, @jc-lab! CloudServer is a part of Zenko and I would also suggest asking your question on [Zenko forum](https://forum.zenko.io/). It is generally a faster way to get answers :)

**Comment by dora-korpar** [comment]
Hi @jc-lab,
The 'read' ACL doesn't allow getting objects, it only allows listing them.
To manage permissions for getting objects, you'd need to use bucket policies. Otherwise, by default only the bucket owner will be allowed to get objects.

Hope this helps!

**Comment by rahulreddy** [comment]
Closing, @jc-lab Please reopen if the issue persists.
