### ISSUE TITLE
Can't connect via hostname when docker containers at the same network

### ISSUE THREAD

**Issue by AhmedBHameed** [scality/cloudserver#3653]
I have a back-end server written with node. It is hosted among other services in `docker-compose` file.

The following configuration for `s3server`:

```yml
  s3server:
    hostname: s3server
    container_name: s3server
    image: scality/s3server:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - starlink   # The services are all network bridged.
    volumes:
      - ./s3data:/usr/src/app/localData
      - ./s3metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - SSL="FALSE"
      # - ./s3config.json:/usr/src/app/config.json
    logging:
      driver: none
```

The server using this peace of code:

```typescript
import {S3} from 'aws-sdk';
import environment from 'src/config/environment';
import logger from 'src/services/Logger';

const {s3} = environment;

const s3Client = new S3({
  sslEnabled: false,
  endpoint: `s3server:8000`,
  signatureCache: false,
  signatureVersion: 'v4',
  region: 'us-east-1',
  s3ForcePathStyle: true,
  accessKeyId: s3.accessKeyId,
  secretAccessKey: s3.secretAccessKey,
});

export async function initS3Server() {
  try {
    const {Buckets} = await s3Client.listBuckets().promise();

    Buckets?.forEach(({Name}) => {
      console.log('🚀 ~ file: upload.js ~ line 25 ~ Buckets.forEach ~ Name =>>>> ', Name);
    });
    if (!Buckets?.length) {
      await s3Client
        .createBucket(
          {
            Bucket: s3.bucketName,
          },
          (error, data) => {
            if (error) {
              console.error('Error while creating your bucket.', error);
            } else {
              console.log(`Bucket "${s3.bucketName}" created`, data.Location);
            }
          }
        )
        .promise();
    }
  } catch (error) {
    logger.error('', error);
  }
}

initS3Server();
```

I'm getting the following error

```bash
{
core_service      |   message: 'Could not parse the specified URI. Check your restEndpoints configuration.',
core_service      |   code: 'InvalidURI',
core_service      |   region: null,
core_service      |   time: 2021-06-06T20:44:06.723Z,
core_service      |   requestId: '390359de7f4099c2d680',
core_service      |   extendedRequestId: '390359de7f4099c2d680',
core_service      |   cfId: undefined,
core_service      |   statusCode: 400,
core_service      |   retryable: false,
core_service      |   retryDelay: 23.546135460377073,
core_service      |   level: 'error',
core_service      |   stack: 'InvalidURI: Could not parse the specified URI. Check your restEndpoints configuration.\n' +
core_service      |     '    at Request.extractError (/usr/core_service/node_modules/aws-sdk/lib/services/s3.js:718:35)\n' +
core_service      |     '    at Request.callListeners (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
core_service      |     '    at Request.emit (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
core_service      |     '    at Request.emit (/usr/core_service/node_modules/aws-sdk/lib/request.js:688:14)\n' +
core_service      |     '    at Request.transition (/usr/core_service/node_modules/aws-sdk/lib/request.js:22:10)\n' +
core_service      |     '    at AcceptorStateMachine.runTo (/usr/core_service/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
core_service      |     '    at /usr/core_service/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
core_service      |     '    at Request.<anonymous> (/usr/core_service/node_modules/aws-sdk/lib/request.js:38:9)\n' +
core_service      |     '    at Request.<anonymous> (/usr/core_service/node_modules/aws-sdk/lib/request.js:690:12)\n' +
core_service      |     '    at Request.callListeners (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n' +
core_service      |     '    at Request.emit (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
core_service      |     '    at Request.emit (/usr/core_service/node_modules/aws-sdk/lib/request.js:688:14)\n' +
core_service      |     '    at Request.transition (/usr/core_service/node_modules/aws-sdk/lib/request.js:22:10)\n' +
core_service      |     '    at AcceptorStateMachine.runTo (/usr/core_service/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
core_service      |     '    at /usr/core_service/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
core_service      |     '    at Request.<anonymous> (/usr/core_service/node_modules/aws-sdk/lib/request.js:38:9)\n' +
core_service      |     '    at Request.<anonymous> (/usr/core_service/node_modules/aws-sdk/lib/request.js:690:12)\n' +
core_service      |     '    at Request.callListeners (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n' +
core_service      |     '    at callNextListener (/usr/core_service/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n' +
core_service      |     '    at IncomingMessage.onEnd (/usr/core_service/node_modules/aws-sdk/lib/event_listeners.js:313:13)\n' +
core_service      |     '    at IncomingMessage.emit (events.js:327:22)\n' +
core_service      |     '    at IncomingMessage.EventEmitter.emit (domain.js:483:12)',
core_service      |   timestamp: '2021-06-06 20:44:06'
core_service      | }
```

As you see, i'm using hostname of container `s3server` to initiate the connection. I expected to work since the connection is established with no error but when the code comes to the listing buckets, it trigger the above error.

It is strange that if I use ip address of `s3server` instead of hostname, it works perfectly with no issues. That is not ideal since we are not using a static ip for our servers and we need to count on hostname instead.

Any idea what can cause this isssue or how to solve?

**Comment by AhmedBHameed** [comment]
I've solved the issue by assigning static IP to docker container.

Closing this issue.
