### ISSUE TITLE
{"name":"S3","time":1708457225794,"error":{"code":"ETIMEDOUT","info":"operation put timed out"},"level":"fatal","message":"error writing usersBucket attributes to metadata","hostname":"sdcr1p3c1na.node.strato","pid":63}

### ISSUE THREAD

**Issue by kevinnaik-absa** [scality/cloudserver#5540]
--------------------------------------------------------------------------------

## Bug report information

container crashes out on error:
{"name":"S3","time":1708457225794,"error":{"code":"ETIMEDOUT","info":"operation put timed out"},"level":"fatal","message":"error writing usersBucket attributes to metadata","hostname":"sdcr1p3c1na.node.strato","pid":63}

### Description

container crashes out on timeout error on startup

### Steps to reproduce the issue

Please provide steps to reproduce, including full log output

### Actual result

Describe the results you received

### Expected result

Describe the results you expected

### Additional information

{"name":"S3","time":1708457225794,"error":{"code":"ETIMEDOUT","info":"operation put timed out"},"level":"fatal","message":"error writing usersBucket attributes to metadata","hostname":"sdcr1p3c1na.node.strato","pid":63}
/usr/src/app/lib/metadata/bucketfile/backend.js:47
                    throw (errors.InternalError);
                    ^

Error: InternalError
    at ArsenalError (/usr/src/app/node_modules/arsenal/lib/errors.js:5:9)
    at Object.keys.filter.forEach.index (/usr/src/app/node_modules/arsenal/lib/errors.js:29:31)
    at Array.forEach (native)
    at errorsGen (/usr/src/app/node_modules/arsenal/lib/errors.js:28:12)
    at Object.<anonymous> (/usr/src/app/node_modules/arsenal/lib/errors.js:35:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

npm ERR! Linux 3.10.0-957.12.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "start_s3server"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start_s3server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s3@7.0.0 start_s3server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 3.10.0-957.12.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s3@7.0.0 start script 'npm-run-all --parallel start_dmd start_s3server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_dmd start_s3server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

--------------------------------------------------------------------------------

## Feature Request

(delete this section (everything between the lines) if you're not requesting
a feature but reporting a bug)

### Proposal

Describe the feature

### Current behavior

What currently happens

### Desired behavior

What you would like to happen

### Use case

Please provide use cases for changing the current behavior

### Additional information

- Is this request for your company? Y/N
  - If Y: Company name: A BANK
  - Are you using any Scality Enterprise Edition products (RING, Zenko EE)? N
- Are you willing to contribute this feature yourself?
- Position/Title:
- How did you hear about us?

--------------------------------------------------------------------------------

**Comment by dprabah** [comment]
If you are trying with NFS,
and it is locally mounted,
you can use the mounted volume directly.
